### ISSUE TITLE
Add Arguments Support 🚀

### ISSUE THREAD

**Issue by zntfdr** [zntfdr/Selenops#2]
The script (not the Xcode Playground, for obvious reasons) [can take some arguments](https://krakendev.io/blog/scripting-in-swift#block-yui_3_17_2_1_1435871948122_32917) when called from the terminal.

It would be great if Selenops could support these three arguments: 

1. [``startUrl``](https://github.com/zntfdr/Selenops/blob/master/Script/Selenops.swift#L12);
2. [``wordToSearch``](https://github.com/zntfdr/Selenops/blob/master/Script/Selenops.swift#L13);
3. [``maximumPagesToVisit``](https://github.com/zntfdr/Selenops/blob/master/Script/Selenops.swift#L14);

**Comment by grayma** [comment]
Hey! I just submitted a pull request implementing these. It's the first time I've contributed to a GitHub project, so if you have any feedback feel free to give it 😄. I hope this does the job.

**Comment by zntfdr** [comment]
Hi Matthew,

You're awesome! Thank you so much for this.

I'm on holiday (Mac-less 😱) until Sunday: I will check the PR once I'm back home.

Thank you for your patience 😊

_____________________________

**Comment by zntfdr** [comment]
Added in https://github.com/zntfdr/Selenops/commit/f68465c3b47d7679b159c9aeab607f69755c5b88 ,  thanks @grayma !! 😊
